import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <p>
        <h1 className={styles.title} style={{width:'99vw',height:'9vh',borderBottomColor:'black'}}>
          Welcome to <a style={{color:'#1C94FC'}} href="https://supportchildren.org">supportchildren</a>
      <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimage.flaticon.com%2Ficons%2Fpng%2F512%2F98%2F98756.png&f=1&nofb=1"></img>
        </h1>
  
    
    
    
       </p>

        <p className={styles.description}>
          neki tekst    
        </p>

        <div className={styles.grid} >
          <a href="http://localhost:3000/browser"  className={styles.card}>
            <h2>Browse Campignes &rarr;</h2>
            <p>See the wide range of people you can help right now</p>
          </a>

          <a href="http://localhost:3000/learn" 
           className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>learn more about the children and how they are progressing</p>
          </a>

          <a
            className={styles.card}
          href="http://localhost:3000/kontakt"
          >
            <h2>Want to contact us? &rarr;</h2>
            <p>Just write us an email to the adress () or call us at 4589348</p>
          </a>

          <a
            className={styles.card}
            style={{padding:11}}
          >
            <h2>FAQ &rarr;</h2>
            <p>
We are using a decentrlized system so that we can have more transparency and support children
             </p>
          </a>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{'dodgecoin crew '}
                 </a>
      </footer>
    </div>
  )
}
